---
title: "Module 2 Project"
author: "Chongxuan Bi"
date: "`r Sys.Date()`"
output: pdf_document
---


```{r}
library(tidyverse)
data = read_csv('BodyFat.csv')
data
```

```{r}
boxplot(data$WEIGHT)
temp = (data$ADIPOSITY * (data$HEIGHT)^2 / 703)[data$WEIGHT>250]
temp

boxplot(data$HEIGHT)
temp = sqrt(703 * data$WEIGHT/data$ADIPOSITY)[data$HEIGHT < 60]
data$HEIGHT[data$HEIGHT< 60] = temp

boxplot(data$ADIPOSITY)
temp = (703 * data$WEIGHT / (data$HEIGHT)^2)[data$ADIPOSITY > 33.3]
temp

boxplot(data$BODYFAT)
plot(data$DENSITY, data$BODYFAT)

```

```{r}
library(reshape2)
cor_mat = cor(data)
cor_mat[lower.tri(cor_mat)] = NA
cor_mat = round(cor_mat, 2)
melted_cormat = melt(cor_mat)
heatmap = ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()

heatmap +
geom_text(aes(Var2, Var1, label = value), color = "black", size = 2.5) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))


```
```{r}
library(caret)
set.seed(123)
training_index = createDataPartition(data$BODYFAT, p = 0.8, list = F)
training = data[training_index,]
testing = data[-training_index,]
```

```{r}
slr = lm(BODYFAT ~ ABDOMEN, data = training)
summary(slr)
plot(training$ABDOMEN,training$BODYFAT)
points(training$ABDOMEN,slr$fitted.values, col = 'red')
plot(slr)
rmse = sqrt(mean((predict(slr, testing) - testing$BODYFAT)^2))
rmse


slr_all = lm(BODYFAT ~ ABDOMEN, data = data)
summary(slr_all)
plot(slr_all)

```

Alternatively,
```{r}
lr = lm(BODYFAT ~ WEIGHT + HEIGHT + AGE, data = training)
summary(lr)
plot(lr)
rmse = sqrt(mean((predict(lr, testing) - testing$BODYFAT)^2))
rmse
```

```{r}
intercept_model = lm(BODYFAT ~ 1, data = training)
all_model = lm(BODYFAT ~ . - IDNO - DENSITY, data = training)
forward = step(object = intercept_model, scope = formula(all_model), direction = 'forward', k = log(nrow(training)))
summary(forward)
plot(forward)
rmse = sqrt(mean((predict(forward, testing) - testing$BODYFAT)^2))
rmse
```

```{r}
library(rpart)
tree = rpart(BODYFAT ~ . - IDNO - DENSITY, data = training)
rmse = sqrt(mean((predict(tree, testing) - testing$BODYFAT)^2))
rmse

```
```{r}
library(randomForest)
rf = randomForest(BODYFAT ~ . - IDNO - DENSITY, data = training, maxnodes = 8)
rmse = sqrt(mean((predict(rf, testing) - testing$BODYFAT)^2))
rmse
```