---
title: "Module 2 Project"
author: "Chongxuan Bi"
date: "`r Sys.Date()`"
output: pdf_document
---

# Read data
```{r}
library(tidyverse)
<<<<<<< HEAD:code/module2_project.Rmd
data = read_csv('../data/BodyFat.csv')
data
=======
data = read_csv('BodyFat.csv')
>>>>>>> 4bcc6ea (revised code and shinyapp):module2_project.Rmd
```

# Data Cleaning
```{r}
# Check whether recomputed data differ a lot from the original. If yes, replace.
boxplot(data$WEIGHT, main = 'Weight')
temp = (data$ADIPOSITY * (data$HEIGHT)^2 / 703)[data$WEIGHT>250]


boxplot(data$HEIGHT, main = 'Height')
temp = sqrt(703 * data$WEIGHT/data$ADIPOSITY)[data$HEIGHT < 60]
data$HEIGHT[data$HEIGHT< 60] = temp

boxplot(data$ADIPOSITY, main = 'Adiposity')
temp = (703 * data$WEIGHT / (data$HEIGHT)^2)[data$ADIPOSITY > 33.3]

boxplot(data$BODYFAT, main  = 'Body Fat')
plot(data$DENSITY, data$BODYFAT, xlab = 'Density', ylab = 'Body Fat')

```
# Modeling
## Create a correlation plot
```{r, warning=F}
library(reshape2)
cor_mat = cor(data)
cor_mat[lower.tri(cor_mat)] = NA
cor_mat = round(cor_mat, 2)
melted_cormat = melt(cor_mat)
heatmap = ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()

heatmap +
geom_text(aes(Var2, Var1, label = value), color = "black", size = 2.5) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))


```
## Train/Test Split
```{r}
library(caret)
set.seed(123)
training_index = createDataPartition(data$BODYFAT, p = 0.8, list = F)
training = data[training_index,]
testing = data[-training_index,]
```

## Simple Linear Regression
```{r}
slr = lm(BODYFAT ~ ABDOMEN, data = training)
summary(slr)
par(mfrow = c(2,2))
plot(slr)
rmse_slr = sqrt(mean((predict(slr, testing) - testing$BODYFAT)^2))
rmse_slr
```

## Multiple Linear Regression

It uses the three variables that have the highest correlation with body fat.
```{r}
lr = lm(BODYFAT ~ WEIGHT + HEIGHT + AGE, data = training)
summary(lr)
par(mfrow = c(2,2))
plot(lr)
rmse_lr = sqrt(mean((predict(lr, testing) - testing$BODYFAT)^2))
rmse_lr
```
## Forward Selection
```{r}
intercept_model = lm(BODYFAT ~ 1, data = training)
all_model = lm(BODYFAT ~ . - IDNO - DENSITY, data = training)
forward = step(object = intercept_model, scope = formula(all_model), direction = 'forward', k = log(nrow(training)))
summary(forward)
par(mfrow = c(2,2))
plot(forward)
rmse_forward = sqrt(mean((predict(forward, testing) - testing$BODYFAT)^2))
rmse_forward
```
## Decision Tree
```{r}
library(rpart)
tree = rpart(BODYFAT ~ . - IDNO - DENSITY, data = training)
rmse_tree = sqrt(mean((predict(tree, testing) - testing$BODYFAT)^2))
rmse_tree
```

## Random Forest
```{r}
library(randomForest)
set.seed(123)
rf = randomForest(BODYFAT ~ . - IDNO - DENSITY, data = training, maxnodes = 8, )
rmse_rf = sqrt(mean((predict(rf, testing) - testing$BODYFAT)^2))
rmse_rf
```

## Compare Models
```{r}
plot(c(1, length(lr$coefficients) - 1, length(forward$coefficients) - 1, 10, 8),
     c(rmse_slr, rmse_lr, rmse_forward, rmse_tree, rmse_rf), 
     xlim = c(0, 11), xlab = 'Number of Coefficients', ylab = 'RMSE on Testing')
text(c(1, length(lr$coefficients) - 1, length(forward$coefficients) - 1, 10, 8),
     c(rmse_slr, rmse_lr, rmse_forward, rmse_tree, rmse_rf),
     c('SLR', 'LR', 'forward', 'tree', 'rf'), pos = 4, cex = 0.8)

```

## Final Model
```{r, warning=F}
slr_all = lm(BODYFAT ~ ABDOMEN, data = data)

predict(slr_all, data.frame(ABDOMEN=100), interval = 'prediction', level = 0.95)
predict(slr_all, data.frame(ABDOMEN=100), interval = 'prediction', level = 0.50)

new_df = cbind(data, predict(slr_all, interval='prediction', level = 0.95))
ggplot(new_df, aes(ABDOMEN, BODYFAT)) +
  geom_point() +
  geom_smooth(method = glm) +
  xlab('Abdomen Circumference') +
  ylab('Body Fat (%)') +
  geom_line(aes(y=lwr), color = 'red', lty = 'dashed') +
  geom_line(aes(y=upr), color = 'red', lty = 'dashed')
```